include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    non_constant_identifier_names: false
    lowercase_with_underscores: false
    library_private_types_in_public_api: false
    use_build_context_synchronously: false