name: real_time_track_package
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^7.4.0
  avatar_glow: ^2.0.2
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.18
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.3
  device_info_plus:
    path: packages/device_info_plus
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/
    - assets/flags/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700