name: real_time_track_package
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  avatar_glow: ^3.0.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.0.18
  jwt_decoder: ^2.0.1
  package_info_plus: ^6.0.0
  device_info_plus: ^9.1.2
  url_launcher: ^6.1.11
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  fluttertoast: ^8.2.2
  intl: ^0.19.0
  map_launcher: ^3.1.0
  web_socket_channel: ^2.4.4
  flutter_timezone: ^1.0.8
  timezone: ^0.9.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  assets:
    - assets/
    - assets/flags/
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700